### PR TITLE
Fix Highlight Code Parameter

### PR DESCRIPTION
**Pull request by IanMitchell**
Not sure how to convert strings to booleans in yargs, might be cleaner than checking for `!== 'false'`

### CODE REVIEW

**Comment by tscanlin** [comment]
Hey, thanks for opening the PR! I think you can pass the option as `--no-highlightCode` and it should return a proper boolean instead of a string.

**Comment by IanMitchell** [comment]
So you can! Removed the string check and added a quick note to the ReadMe explaining that trick. Thanks for the pointer!

**Comment by tscanlin** [comment]
Awesome, thank you so much @IanMitchell! :)

**Comment by tscanlin** [comment]
`processmd@4.0.2` is published with this change.

**Comment by IanMitchell** [comment]
Thanks!

**Pull request merged**
